answers-file: answers.yaml
expected-files:
- xebialabs/USAGE-hashicorp-vault.md
- docker-hashicorp-vault/docker-compose.yaml
- docker-hashicorp-vault/vault/Dockerfile
- docker-hashicorp-vault/vault/script/provision.sh
not-expected-files:
- xebialabs.yaml
